import { getHoroscopeBySign } from "@/lib/queries";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Sparkles } from "lucide-react";
import { HoroscopeDatePicker } from "@/components/HoroscopeDatePicker";

interface AstroReadingPageProps {
  params: Promise<{ sign: string }>;
  searchParams: Promise<{ date?: string }>;
}

export default async function AstroReadingPage({ params, searchParams }: AstroReadingPageProps) {
  const resolvedParams = await params;
  const resolvedSearchParams = await searchParams;
  
  // Parse date from query params or use today
  let selectedDate = new Date();
  if (resolvedSearchParams.date) {
    const parsedDate = new Date(resolvedSearchParams.date);
    if (!isNaN(parsedDate.getTime())) {
      selectedDate = parsedDate;
    }
  }
  
  const reading = await getHoroscopeBySign(resolvedParams.sign, selectedDate);

  if (!reading) {
    // If the cron hasn't run yet, we don't 404, we show a premium "calculating" state
    return (
      <div className="w-full max-w-2xl mx-auto py-20 text-center px-4">
        <h1 className="text-4xl font-black font-playfair mb-4 uppercase tracking-tighter italic">
          {resolvedParams.sign}
        </h1>
        <p className="text-slate-500 italic">
          {resolvedSearchParams.date 
            ? `No planetary alignment recorded for this sign on ${selectedDate.toLocaleDateString()}. Try another date.`
            : "Planetary alignments are still being processed for this sign. Check back at the next moon phase."}
        </p>
        <Link href="/horoscopes" className="mt-8 inline-block text-xs font-bold uppercase tracking-widest text-[#E2725B]">Return to Desk</Link>
      </div>
    );
  }

  return (
    <div className="w-full max-w-2xl mx-auto py-8 md:py-16 px-4">
      <Link href="/horoscopes" className="inline-flex items-center text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400 hover:text-[#E2725B] transition-colors mb-12">
        <ArrowLeft size={14} className="mr-2" /> Back to Astro Desk
      </Link>

      {/* Date Picker */}
      <HoroscopeDatePicker currentDate={selectedDate} />

      <div className="relative border-l-2 border-[#E2725B] pl-8 md:pl-12">
        <div className="flex items-center gap-2 text-[#3A7B7A] mb-4">
          <Sparkles size={16} />
          <span className="text-xs font-bold uppercase tracking-widest">Daily Briefing</span>
        </div>

        <h1 className="text-5xl md:text-7xl font-black font-playfair text-black dark:text-[#F9F6F0] mb-6 lowercase tracking-tighter">
          {reading.sign}
        </h1>

        <div className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-10">
          Intelligence for {reading.publishDate.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </div>

        <div className="text-xl md:text-2xl font-medium leading-relaxed text-slate-800 dark:text-slate-200 italic font-serif">
          "{reading.reading}"
        </div>

        <div className="mt-16 pt-8 border-t border-black/5 dark:border-white/5">
          <p className="text-[10px] text-slate-400 uppercase tracking-widest font-bold">
            Generated by Beacon-Hub Celestial Engine &bull; JCLs
          </p>
        </div>
      </div>
    </div>
  );
}