name: secret-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run TruffleHog scan
        uses: trufflesecurity/trufflehog-action@v2
        with:
          format: json
          # scan history and commits
          args: --entropy=False
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
